### ISSUE TITLE
Model Development

### ISSUE THREAD

**Issue by mmiranda222** [Joseph-233/music-recommendation#4]
Create the appropriate model based on the data provided by the data scientists. The main focus in this iteration is not the fine tuning or the optimal accuracy, rather focus on the functionality of the model itself.

**Comment by tatosf** [comment]
The model is complete, we are currently using lgbm to get the user's relationship features to tempo based on play count. Then when a user inputs their heart rate we load the saved model in Streamlit to predict the other song features. With these song features, we then use the Spotify API to get 10 songs using the user features and user profile preferences. We also decided using the API instead of filtering our dataset since we realized our trained model misses some new songs and we found better recommendations this way, but the model is helpful and getting relationships to tempo and other features we then use in the api.
